apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
    - name: {{ .Release.Name }}-port
      port: 8080
      targetPort: 4567
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
